# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3
