# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
