name: Tests
on:
  push:
  pull_request:
jobs:
  test:
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }} / Vault ${{ matrix.vault }}
    strategy:
      fail-fast: false
      matrix:
        # https://endoflife.date/ruby
        ruby: ["3.2", "3.3", "3.4", "4.0"]
        # https://endoflife.date/rails
        rails: ["7.2", "8.0", "8.1"]
        # https://developer.hashicorp.com/vault/docs/enterprise/lts
        vault: ["1.16.3", "1.19.5", "1.20.4", "1.21.2"]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      RAILS_VERSION: ${{ matrix.rails }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: "Install vault cli"
        run: |
          curl -sLo vault.zip "https://releases.hashicorp.com/vault/${{ matrix.vault }}/vault_${{ matrix.vault }}_linux_amd64.zip"
          unzip vault.zip
          mkdir -p "$HOME/bin"
          mv vault "$HOME/bin"
          echo "$HOME/bin" >> "$GITHUB_PATH"
      - name: "Setup tests"
        run: |
          bundle exec rake app:db:create
          bundle exec rake app:db:schema:load
          bundle exec rake app:db:test:prepare
          gem uninstall sqlite3
      - name: "Run tests"
        run: bundle exec rake spec

permissions:
  contents: read
